/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmiclient;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rmiserver.IUserFunc;
import rmiserver.User;

/**
 *
 * @author Quan Duc Loc CE140037 (SE1401)
 */
public class frmDepositWithdraw extends javax.swing.JFrame {

    String action;
    User userInfo;
    IUserFunc iUser;

    /**
     * Creates new form frmDepositWithdraw
     *
     * @param action
     * @param userInfo
     */
    public frmDepositWithdraw(String action, User userInfo) {
        initComponents();

        this.action = action;
        this.userInfo = userInfo;

        txtPhoneNumber.setText(userInfo.getPhone());
        txtBalance.setText(String.valueOf(userInfo.getMoney()) + " VND");

        if (action.equals("deposit")) {
            this.setTitle("Deposit Transaction");
            lblAmount.setText("Deposit Amount");
            btnConfirm.setText("Confirm Deposit");
        } else if (action.equals("withdraw")) {
            this.setTitle("Withdraw Transaction");
            lblAmount.setText("Withdraw Amount");
            btnConfirm.setText("Confirm Withdraw");
        }

        try {
            /* Connects to server */
            iUser = (IUserFunc) Naming.lookup("rmi://localhost:70/UserFunctions");
        } catch (NotBoundException ex) {
            Logger.getLogger(frmDepositWithdraw.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(frmDepositWithdraw.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(frmDepositWithdraw.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAmount = new javax.swing.JLabel();
        lblCurrentBalance = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAmount.setText("Deposit Amount");

        lblCurrentBalance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCurrentBalance.setText("Current Balance");

        txtBalance.setEditable(false);
        txtBalance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnConfirm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnConfirm.setText("Confirm Deposit");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        lblPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPhoneNumber.setText("Your Phone Number");

        txtPhoneNumber.setEditable(false);
        txtPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCurrentBalance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBalance)
                            .addComponent(txtAmount)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentBalance)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmount)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnConfirm)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        switch (action) {
            case "deposit":

                String txtAmountString = txtAmount.getText();
                int txtAmountInt = -1;
                boolean error = false;
                User result = null;

                if (txtAmountString == null || txtAmountString.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please enter a number in \"Deposit Amount\" field", "Input Notification", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    try {
                        txtAmountInt = Integer.parseInt(txtAmountString);
                    } catch (NumberFormatException ex) {
                        error = true;
                    }

                    if (error) {
                        JOptionPane.showMessageDialog(this, "Please enter a number in \"Deposit Amount\" field", "Input Notification", JOptionPane.INFORMATION_MESSAGE);
                    } else if (!error && (txtAmountInt < 1000 || txtAmountInt > userInfo.getDeposit_lim())) {
                        JOptionPane.showMessageDialog(this, "Please enter a value between 1000 and " + userInfo.getDeposit_lim() + " (inclusive)", "Input Notification", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        try {
                            result = iUser.deposit(userInfo, txtAmountInt);
                        } catch (RemoteException ex) {
                            Logger.getLogger(frmDepositWithdraw.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        int deposit_lim = userInfo.getDeposit_lim();

                        if (result.getDeposit_lim() != deposit_lim && result.getMoney() != userInfo.getMoney()) {
                            JOptionPane.showMessageDialog(this, "Deposit successfully! New Account Balance is " + result.getMoney(), "Transaction Completed!", JOptionPane.INFORMATION_MESSAGE);
                            userInfo = result;
                        } else if (result.getDeposit_lim() != deposit_lim && result.getMoney() == userInfo.getMoney()) {
                            JOptionPane.showMessageDialog(this, "Deposit failed!", "Transaction Failed!", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(this, "Total deposit amount exceeds limit!", "Transaction Failed!", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }
                break;

            case "withdraw":

                break;
        }
    }//GEN-LAST:event_btnConfirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCurrentBalance;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
